### ISSUE TITLE
{"error":"sequence item 0: expected str instance, Line found"}

### ISSUE THREAD

**Issue by loghyr** [ietf-tools/author-tools#490]
### Describe the issue

To reproduce:

git clone git@github.com:loghyr/flexfilesv2.git
cd flexfilesv2
make

Submit resulting file draft-haynes-nfsv4-flexfiles-v2-00.xml  to https://author-tools.ietf.org/idnits

Or submit the following: (might have to rename to .xml)
[draft-haynes-nfsv4-flexfiles-v2-00.txt](https://github.com/user-attachments/files/15813948/draft-haynes-nfsv4-flexfiles-v2-00.txt)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@loghyr, This is a xml2rfc bug.
The way https://author-tools.ietf.org/idnits works is, it creates a text file from the XML you submit.
Because idints v2 only works with text files.
You can use experimental [idnits v3](https://author-tools.ietf.org/idnits3) to test XML files without converting to text under the hood.

The error you get is from `xml2rfc`:
```
root@4d23dc73e717:~/xml2rfc# xml2rfc draft-haynes-nfsv4-flexfiles-v2-00.xml
Warning: /root/xml2rfc/rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
Warning: /root/xml2rfc/rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
Warning: /root/xml2rfc/rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
Warning: /root/xml2rfc/rfc2629-xhtml.ent is no longer needed as the special processing of non-ASCII characters has been superseded by direct support for non-ASCII characters in RFCXML.
/root/xml2rfc/draft-haynes-nfsv4-flexfiles-v2-00.xml(18): Warning: Setting consensus="true" for IETF STD document (this is not the schema default, but is the only value permitted for this type of document)
/root/xml2rfc/draft-haynes-nfsv4-flexfiles-v2-00.xml(2599): Warning: Unused reference: There seems to be no reference to [RFC8435] in the document
/root/xml2rfc/draft-haynes-nfsv4-flexfiles-v2-00.xml(336): Warning: Was asked to render a deprecated element: <list>
    c: '<Element list at 0xffff9876cfe0>'
Traceback (most recent call last):
  File "/usr/local/bin/xml2rfc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/run.py", line 730, in main
    writer.write(filename)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 344, in write
    text = self.process()
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 302, in process
    lines = self.render(self.root, width=72, joiners=joiners)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 368, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 3064, in render_rfc
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 557, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 368, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 2242, in render_middle
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 557, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 368, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 3335, in render_section
    lines = self.ljoin(lines, c, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 557, in ljoin
    res = mklines(self.render(e, width, **kwargs), e)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 368, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 3767, in render_t
    text = self.inner_text_renderer(e)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 631, in inner_text_renderer
    text += self.render(c, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 368, in render
    res = func(e, width, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xml2rfc/writers/text.py", line 613, in default_renderer
    ctext = "\n\n".join(ctext)
TypeError: sequence item 0: expected str instance, Line found
```

Since this is a `xml2rfc` bug I'll move it there.

**Comment by kesara** [comment]
Looks like the error is because of the `<list>` tag.
It's deprecated in xml2rfc v3 vocabulary.
You can use `<ul>` (unordered list) [^1] or `<ol>` (ordered list) [^2] instead.

[^1]: https://authors.ietf.org/en/rfcxml-vocabulary#ul
[^2]: https://authors.ietf.org/en/rfcxml-vocabulary#ol
